### ISSUE TITLE
Add plugins and other resources support

### ISSUE THREAD

**Issue by Leonardo-DGS** [modrinth/knossos#315]
### Describe the solution you'd like

Support for Modrinth for resources other than mods, like plugins, resource packs, maps, etc.
In this way developers would be more motivated to develop open source plugins, in this way they can make money without charging their plugins.

**Comment by wafflecoffee** [comment]
[honk](https://modrinth.com/plugins) and [honk](https://modrinth.com/resourcepacks)

Datapacks, shaderpacks, and worlds are already on our roadmap. However, we'd rather not have issues open for stuff that's on our roadmap already, since oftentimes these changes are not just backend or just frontend.
