### ISSUE TITLE
Use the "read" state for notifications similarly to GitHub

### ISSUE THREAD

**Issue by Adirelle** [modrinth/knossos#334]
### Is your feature request related to a problem? Please describe.

When following a lot of mods, manually dismissing update notifications can become tedious. And if you open the link, you have to do it in a separate navigator tab, to be able to dismiss the notification, unless you want to go back.

### Describe the solution you'd like

I would like to automatically dismiss a notification when I clicked on it to go to the related mod page.

### Describe alternatives you've considered

* A "dismiss all" button.
* Dismissing all notifications related to a mod when one opens its page.
* Dismissing all notifications related to a mod when one downloads it.
* A profile settings the select how to automatically dismiss a notification (including "do not").

**Comment by wafflecoffee** [comment]
> I would like to automatically dismiss a notification when I clicked on it to go to the related mod page.

This is not a great solution. If my notifications were to disappear after I clicked on them, I would be rather confused.
> A "dismiss all" button.

Added in #250 already

**Comment by wafflecoffee** [comment]
Actually, now that I think about it, an "unread" vs "read" marker would be a good idea, separate from clearing a notification altogether. That's how GitHub does it, and it's a fairly good system. I'm just not entirely sure how we're meant to implement that, because a request to change the state of a notification each time it's opened seems like it would be rather overkill.

**Comment by venashial** [comment]
Notifications seem to already have a read and unread state in the backend, but the notifications are deleted instead of their read state being changed.
