### ISSUE TITLE
Clicking on notification redirects to the wrong url

### ISSUE THREAD

**Issue by luni3359** [modrinth/knossos#349]
### Environment

Website

### Describe the bug

As of lately clicking on mod notifications have started looking weird, redirecting the user to the wrong place and causing a "This page could not be found" error.

![Weird notification entry](https://user-images.githubusercontent.com/16832398/153033617-e793ae47-6c34-4890-b051-9092732b9fae.png)
The first notification is missing `/mod/` and leads to:
https://modrinth.com/HnD1GX6e/version/9v0MYDuP
...while the second one is correct:
https://modrinth.com/mod/ZfQ3kTvR/version/WdNFKue4

### Steps To Reproduce

1. Go to your notifications
1a. Notice how every notification entry has asterisks around the title
2. Click on the notification to download the mod
3. You get a "This page could not be found" error

### Expected behavior

Clicking the notification should lead the user to the correct download page

### Additional context

It's been happening for a while now, maybe something changed in the backend that caused this issue.

**Comment by manuelgrabowski** [comment]
I'm seeing this for every single notification, none of mine are correct. I suppose the second one in your screenshot was generated before the feature broke (as it says "17 days ago").

**Comment by luni3359** [comment]
Yeah, that notification I luckily never dismissed (at that time) so that's why it works, so it's confirmation that this bug only affects notifications created after some change. But just like you mention, notifications have been broken for a while now. 

It's really annoying because I know non-tech savvy users are going to think something is broken and move on to Forge.

**Comment by wafflecoffee** [comment]
I was curious what was causing this, and as I suspected, it was due to a single forward slash.
![EDDDF4E8-19B3-4025-B6A2-9BF7C1FAA6E2](https://user-images.githubusercontent.com/60205699/154401047-6fa75b49-4efd-4bda-932a-3ab1eccf1be7.jpeg)
I'm fairly sure this is accounted for in the master branch -- could you test this [here](https://knossos-git-prod-api-emmaffle.vercel.app/)?
We aren't going to be doing further updates of the production front-end until the release of modpacks, so this may end up continuing to be an inconvenience until then.

**Comment by luni3359** [comment]
The update has gone live and the bug is no longer present.
