### ISSUE TITLE
Can't upload modpack version

### ISSUE THREAD

**Issue by RedstoneGyerek** [modrinth/knossos#430]
### Environment

Website

### Describe the bug

When I try to save the modpack's version, it just doesn't let me to. The little green line on the top starts to fill, but sometimes it just stops, resets or just got a red flash at the end. Idk what to do with this. PLez fix

### Steps To Reproduce

1. Fill all information
2. Click on Save
3. Nothing

### Expected behavior

It should save it.

**Comment by wafflecoffee** [comment]
If I had to guess, you aren't using the correct modpack format; this can only really be obtained via [packwiz](https://github.com/packwiz/packwiz) or [ATLauncher](https://atlauncher.com) at the moment.
The other thing that might be the case here is that you haven't filled out all relevant fields, but we don't really have any way of knowing because the information given here is so minimal.
I'm going to close this since the issue tracker isn't for support (we have a [Discord](https://discord.gg/EUHuJHt) with a channel for this), but rather for proven bugs.

**Comment by RedstoneGyerek** [comment]
Yea, my pack was made with tlauncher.
Thanks for help.

Emma C. Pointer-Null ***@***.***> ezt írta (időpont: 2022.
márc. 26., Szo 1:20):

**Comment by wafflecoffee** [comment]
TLauncher is not supported and will never be supported
