### ISSUE TITLE
Strip any spaces from project ID inputs.

### ISSUE THREAD

**Issue by woodiertexas** [modrinth/knossos#467]
### Is your feature request related to a problem? Please describe.

When copying a project's ID, sometimes spaces will get copied as well and when I go to paste the ID into an input like the dependency input for example, I get an error that the project doesn't exist.

### Describe the solution you'd like

Essentially search for any spaces in project ID inputs and trim them.

This is what I copy when trying to copy the project ID belonging to Quilt Standard Libraries:
`
qvIfYCYJ `
![image](https://user-images.githubusercontent.com/17211100/167286758-15d94159-8f40-4a57-9211-ce4a0ab561e7.png)

**Comment by Mx772** [comment]
When copying, double-click the ID and copy. 
You won't get a return character included. 

If you drag-select you are picking up extra characters. This is the case with any of the fields in `Technical Information` for any mod.
The value is correct in that it doesn't have a return character in it. 
![image](https://user-images.githubusercontent.com/9059161/169432996-3fcaf5a6-a74d-437c-b599-31cc5107daef.png)

Just for reference, if you replace the value of the ID with another value with no spaces/etc. It still happens when you drag-copy.

**Comment by ubionexd** [comment]
It is a really annoying thing so i just fixed it.

**Comment by wafflecoffee** [comment]
Fixed in #484
