### ISSUE TITLE
[Feature Request] Download button colors matching the release type

### ISSUE THREAD

**Issue by RyderBelserion** [modrinth/knossos#836]
### Is your feature request related to a problem? Please describe.

The download buttons on the "Versions" tab are Green even if the release type is set to Alpha or Beta.

### Describe the solution you'd like

It would be nice if the download buttons would match what the release type so Alpha being light red means the download button is light red.

![image](https://user-images.githubusercontent.com/52214219/211177853-c41272be-9f40-44e2-a982-2eee8fbf0a79.png)
![image](https://user-images.githubusercontent.com/52214219/211177885-41e65cd4-54c9-4b35-9885-fa2ba41160e5.png)

2 images of the buttons I am talking about.

### Describe alternatives you've considered

None

### Additional context

Thank you for the platform.

**Comment by 12emin34** [comment]
I feel like downloading potentially unstable builds only meant for testing _should_ be considered a dangerous action.

I had multiple conversations with my little modding team about how to push test versions to users for our upcoming project. We want to gather feedback early on, but I feel like (most) users just ignore alpha/beta labels, and since we will do massive changes in that phase, possibly causing their worlds/configs to break in some cases among other things. 

The user is 100% at fault, but I think this will aid in at least lessening the issue by adding another visual indicator. 

Just wanted to put my perspective of this up here. Thanks for making the best mod platform ever!

**Comment by Prospector** [comment]
I still think that downloading is a very non-dangerous option. The dangerous action is the user installing it on a non-test instance. In the future we could maybe have a way for project authors to have pre-release versions hidden behind an extra filter by default if they tend to release particularly unstable and/or frequent pre-release versions.
